### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by AnnaBhlr** [SNG-Newy/eigenstrapping#1]
Hi,
thanks for providing this extensive package! I did pip install the python dependencies using the provided requirements.txt, followed by pip installing eigenstrapping. Everything went smoothly but I then got an error while `import geometry from eigenstrapping`:
`ImportError: cannot import name '_stats' from 'scipy.ndimage.measurements' (/Library/Frameworks/Python.framework/V ersions/3.9/lib/python3.9/site-packages/scipy/ndimage/measurements.py)`
What's the issue here? Scipy was successfully installed...

**Comment by nikitas-k** [comment]
Hi, yes this is an ongoing issue with the obsolete netneurotools pip package. As a temporary workaround, I would recommend installing the netneurotools package at this upstream fork: https://github.com/nikitas-k/netneurotools_scipyfix/tree/main

Then reinstalling eigenstrapping.

**Comment by nikitas-k** [comment]
Updated README to reflect workaround with commit:
https://github.com/SNG-Newy/eigenstrapping/commit/465eae8da24d16841e14cc566a12262b2c87542b

**Comment by nikitas-k** [comment]
Working as of https://github.com/SNG-Newy/eigenstrapping/commit/5bcfad2ddb3f9582bcedd4d3edaa10443a08412d

**Comment by VinceBaz** [comment]
Hi @nikitas-k, we released a new version of netneurotools 😄 ([0.2.4](https://github.com/netneurolab/netneurotools/releases/tag/0.2.4)). So this toolbox should now work with the pip version of netneurotools!

**Comment by nikitas-k** [comment]
Oh, fantastic! Thanks @VinceBaz. Approved #6
