### ISSUE TITLE
making sense of the method

### ISSUE THREAD

**Issue by astudenova** [SNG-Newy/eigenstrapping#3]
Hi!

I was following the tutorial and created `SurfaceEigenstrapping` class with my data. When I am plotting the `eigen.reconstructed_data` it looks much smoother than my original data. Moreover, residuals seem to carry some information. I am using 1000 eigenmodes. Should it be like this? Could you advise what I need to change?

Here is my code
```
src = mne.setup_source_space(subject, spacing='oct6', subjects_dir=subjects_dir, add_dist=False, n_jobs=10)
vox16_to_vox8 = {ivox:i for i, ivox in enumerate(src[0]['vertno'])}
used_tris_dsmp = [[vox16_to_vox8[tri[0]], vox16_to_vox8[tri[1]], vox16_to_vox8[tri[2]]] for tri in src[0]['use_tris']]
surface=(src[0]['rr'][src[0]['inuse'].astype(bool)].T, used_tris_dsmp)
tria = TriaMesh(surface[0], surface[1])
evals, emodes = calc_eig(tria, 1000, False)

eigen = SurfaceEigenstrapping(
    emodes=emodes,
    evals=evals,
    data=data[:4098],
    num_modes=1000,
    save_rotations=True,
    normalize=False
)
```

**Comment by nikitas-k** [comment]
Hi Alina, thanks for posting this, and I'm sorry I didn't get back sooner, I was away for the weekend. I'm afraid I don't really know what you mean by "much smoother" unless I was to see an image, is it possible to send this through (you could send it directly to my email if posting on this public github is a concern)? It may be that 1000 modes isn't enough to capture the variation in your data, particularly if it's spatially noisy (i.e. not smooth). I would know more if I had a picture.

If you're finding that the residuals contain information, you can always add them back in by permuting them, although we suggest in the preprint to only permute them after adding more modes stops adding reconstruction of the effective variance. In other words, only when it's no longer possible to add more modes to capture the spatial structure. This may be at N/2 (where N is the number of vertices in the mesh) or around there based on our testing. So if you're finding that ~2000 modes is still not enough to capture the spatial structure of your data, then you can add the permuted residuals by adding the `permute=True` flag to the `SurfaceEigenstrapping` class. This should help with capturing any fine-grained spatial information that isn't quite captured by the higher-order modes.

I think it's also worth stressing that the fsaverage 4k mesh isn't something we've extensively tested on either, so there may be idiosyncrasies with the modes in that mesh that we're not aware of. But we'll try our best!

**Comment by nikitas-k** [comment]
Something I should also mention is that we treat the medial wall in the mesh as a boundary by removing it using the `brainspace` and `vtk` libraries, which is one of the reasons why we offer pre-generated modes. We have 4k modes now, which you can download either from the OSF repository: https://osf.io/mabr9/files/osfstorage (`space-fsLR_den-4k_hemi-{hemi}_{emodes or evals}.txt`) or through the `eigenstrapping.datasets.fetch_data` method:

```
from eigenstrapping.datasets import fetch_data
emodes = fetch_data(name='eigenmodes', space='fsLR', den='4k', format='emodes')
evals = fetch_data(name='eigenmodes', space='fsLR', den='4k', format='evals')
emodes_lh, emodes_rh = emodes
evals_lh, evals_rh = evals
```

although then you would have to make sure that your brain map also defines the medial wall as a "boundary" (i.e. nans), or provide a medial wall mask so the `SurfaceEigenstrapping` class ignores the medial wall.

**Comment by astudenova** [comment]
Thank you for your answer! 

Please see attached the images. In general, I expected to see reconstructed data being close to the original. Now, I'm trying to match my expectations with what I see. Do you think it is close enough? 

Original data (EEG)

![brain_lh_data](https://github.com/SNG-Newy/eigenstrapping/assets/76951559/1520b6da-2cdd-4f31-800c-ecc4cced99bf)

Reconstructed from `eigen.reconstructed_data`

![brain_lh_eig_recostructed](https://github.com/SNG-Newy/eigenstrapping/assets/76951559/69148b6e-4f7c-4600-bdf0-76c86508af4a)

Residuals from `eigen.residuals`

![brain_lh_eig_residuals](https://github.com/SNG-Newy/eigenstrapping/assets/76951559/fd655a3d-b6cc-4fd9-a959-8099a59b9c28)

**Comment by nikitas-k** [comment]
Thanks for the images! I see what you mean, could you try to reconstruct with more modes (say, 2000) and post what that looks like?

**Comment by SNG-Newy** [comment]
Hi Alina, how was it all going? If you didn't need any more assistance I'll be closing this in a week or so

**Comment by astudenova** [comment]
Hi! I think I still cannot make a decision to accept (or not) the level of detail that is left in the residuals. But it is not a technical issue. So please close this thread.

**Comment by nikitas-k** [comment]
All good, we can leave it open if you're still working on this

**Comment by astudenova** [comment]
I think there is no longer an issue with either the method or the code. So the ticket can be closed.
